#!/usr/bin/env python3
"""
Smoke-test the Custom Hooks API so you can confirm your backend receives events.

Looks for a ``.env`` file in this order (first file found wins): the ``custom-hooks-sdk-py``
directory, the parent directory (e.g. monorepo root), then the current working directory.

Uses ``python-dotenv`` when installed; otherwise parses simple ``KEY=VALUE`` lines from that
file with the standard library. Variables already set in the process environment are not
overwritten.

Usage::

    # Create custom-hooks-sdk-py/.env with PERMISO_API_KEY=... then:
    python examples/send_test_event.py

Or override for one run::

    PERMISO_API_KEY=your-secret python examples/send_test_event.py

Optional env:

- ``PERMISO_BASE_URL`` — override API base (default: https://alb.permiso.io)
- ``SKIP_END_RUN`` — set to ``1`` to skip the final ``stop`` event
"""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent


def _candidate_env_files() -> list[Path]:
    """Paths to try, most specific first (first existing file is loaded)."""
    return [
        _ROOT / ".env",
        _ROOT.parent / ".env",
        Path.cwd() / ".env",
    ]


def _load_env_manual(path: Path) -> None:
    """
    Minimal .env parser (stdlib only). Matches common KEY=VALUE lines; does not
    override variables already set in the process environment (same as python-dotenv default).
    """
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError:
        return
    if raw.startswith("\ufeff"):
        raw = raw[1:]
    for line in raw.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].lstrip()
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        if not key:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        if key not in os.environ:
            os.environ[key] = value


def _load_env_file() -> None:
    path_to_load: Path | None = None
    for path in _candidate_env_files():
        if path.is_file():
            path_to_load = path
            break
    if path_to_load is None:
        return

    try:
        from dotenv import load_dotenv

        load_dotenv(path_to_load)
    except ImportError:
        _load_env_manual(path_to_load)


_load_env_file()

sys.path.insert(0, str(_ROOT / "src"))

from permiso_custom_hooks import (  # noqa: E402
    PermisoCustomHooksClient,
    PermisoCustomHooksConfig,
    PermisoCustomHooksError,
)


def main() -> None:
    api_key = os.environ.get("PERMISO_API_KEY", "").strip()
    if not api_key:
        print(
            "Missing PERMISO_API_KEY. Add it to custom-hooks-sdk-py/.env, export it in the "
            "shell, or pass it for one run: PERMISO_API_KEY=... python examples/send_test_event.py",
            file=sys.stderr,
        )
        sys.exit(1)

    base_url = os.environ.get("PERMISO_BASE_URL")
    if base_url:
        config = PermisoCustomHooksConfig(api_key=api_key, base_url=base_url)
        resolved_base = base_url.rstrip("/")
    else:
        config = PermisoCustomHooksConfig(api_key=api_key)
        resolved_base = "https://alb.permiso.io"

    client = PermisoCustomHooksClient(config)
    print(f"Posting to {resolved_base}/hooks\n")

    try:
        print("run_id (generated by client):", client.get_run_id())

        start = client.send_event("session_start")
        print("session_start:", json.dumps(start, indent=2))

        ping = client.send_event(
            "sdk_example_ping",
            {
                "source": "custom-hooks-sdk-py/examples/send_test_event.py",
                "sentAt": datetime.now(timezone.utc).isoformat(),
                "message": "Smoke test — check your backend / dashboard for this payload.",
            },
        )
        print("\nsdk_example_ping:", json.dumps(ping, indent=2))

        if os.environ.get("SKIP_END_RUN") == "1":
            print("\nSKIP_END_RUN=1 — not sending stop.")
            return

        stop = client.end_run()
        print("\nstop (end_run):", json.dumps(stop, indent=2))
        print("new run_id after end_run:", client.get_run_id())
        print("\nDone. If your backend is wired correctly, you should see these events there.")
    except PermisoCustomHooksError as err:
        print("\nPermisoCustomHooksError:", err, file=sys.stderr)
        if err.status is not None:
            print("HTTP status:", err.status, file=sys.stderr)
        if err.body is not None:
            print("Body:", err.body, file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
